### ISSUE TITLE
master todo list

### ISSUE THREAD

**Issue by mzhang28** [easyctf/openctf#30]
- [ ] user registration
  - [ ] oauth with google and github and possibly ctf calendar
  - [ ] edit user settings
    - [ ] verify/edit email
    - [ ] two factor auth
- [ ] admin panel
  - [ ] manage users
  - [ ] manage teams
  - [ ] problem editor
    - [ ] problem importer from github and other sources maybe file upload?
  - [ ] export everything (backup)
- [ ] problems list
  - [ ] block before/after competition
  - [ ] filtering options
- [ ] shell server
  - [ ] chroot
- [ ] programming judge
  - [ ] supporting more languages? possibly
- [ ] run separate web challenge containers
- [ ] manager interface for all containers
