### ISSUE TITLE
master todo list

### ISSUE THREAD

**Issue by mzhang28** [easyctf/openctf#33]
feel free to comment if anything seems missing

- [ ] user registration
  - [ ] team creation
    - [ ] invite users to teams, request to join teams
  - [ ] email verification
  - [ ] two-factor auth
  - [ ] oauth login with gmail/github/others
- [ ] admin panel
  - [ ] problem editing panel
    - [ ] upload files
    - [ ] autogen files
    - [ ] programming grader
  - [ ] themes
- [ ] actual competition
  - [ ] block certain pages before competition
  - [ ] end competition on time
  - [ ] ctftime integration (send scores to ctftime)
  - [ ] bonus points
  - [ ] problems page
    - [ ] sort/filter by category
    - [ ] card view as well as list view
- [ ] github integration
  - [ ] problem import
- [ ] manager that's able to launch/drop containers
  - [ ] launch containers for challenges (webchal)
  - [ ] scale containers as necessary
- [ ] a real logging solution.....
- [ ] documentation......
